import React from 'react';
import '../pages/Policy.css';

const PrivacyPolicy = () => {
  return (
    <div className="policy-container">
      <div className="container">
        <h1 className="policy-title">PRIVACY POLICY</h1>
        <div className="policy-content">
          <p>
            This Privacy Policy describes how Herma ("we," "us," or "our") collects, uses, and handles information when you use our AI model routing service, website, and related products (collectively, the "Service"). By using the Service, you agree to the practices described in this policy.
          </p>

          <h2>1. INFORMATION WE COLLECT</h2>

          <h3>Account Information</h3>
          <p>
            When you create an account, we collect your name, email address, and password. You may optionally provide a company name. Passwords are stored using industry-standard one-way hashing and are never stored in plaintext.
          </p>

          <h3>Usage Metadata</h3>
          <p>
            When you use the Service, we collect operational metadata about each request, including: the AI model selected, token counts, response latency, cost, timestamps, and request identifiers. This data is used for billing, service operation, analytics, and to provide you with usage reporting in your dashboard.
          </p>

          <h3>Derivative Performance Metrics</h3>
          <p>
            To improve our routing algorithms and service quality, we generate and store anonymized derivative metrics about interaction characteristics. These metrics describe structural properties of interactions — such as query type (e.g., coding, analysis), complexity level, and topic domain — without containing any actual conversation content. Derivative metrics are generated by AI analysis and stored separately from any content you provide.
          </p>

          <h3>Payment Information</h3>
          <p>
            Payments are processed by Stripe. We do not store your credit card number or full payment details on our servers. We receive confirmation of successful payments and record transaction amounts in your account ledger.
          </p>

          <h3>Device and Browser Information</h3>
          <p>
            We automatically collect standard technical information such as IP address, browser type, device type, operating system, and general geographic location. We use analytics tools to understand how users interact with our website.
          </p>

          <h2>2. HOW WE USE YOUR INFORMATION</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, operate, and maintain the Service</li>
            <li>Process payments and maintain your credit balance</li>
            <li>Improve our AI model routing algorithms and service quality</li>
            <li>Provide usage reporting and account management features</li>
            <li>Monitor for abuse, fraud, and technical issues</li>
            <li>Ensure safety and prevent misuse of the Service</li>
            <li>Comply with legal obligations</li>
            <li>Communicate with you about the Service, including updates and support</li>
          </ul>

          <h2>3. CONTENT HANDLING</h2>
          <p>
            We process your inputs and outputs in real-time to deliver AI model responses. We do not use your content to train AI models. We collect anonymized derivative metrics about interaction characteristics (such as query type and routing performance) to improve our service. Content is encrypted and handled in accordance with data minimization principles.
          </p>
          <p>
            To provide personalization features, we may extract and store encrypted summaries of your stated preferences and relevant context from conversations. These encrypted summaries are used solely to personalize your experience and are not accessible in readable form to our team.
          </p>

          <h2>4. DATA RETENTION</h2>
          <p>
            Account information is retained for as long as your account is active or as needed to provide you with the Service. Usage metadata is retained for billing, analytics, and service improvement purposes. Derivative performance metrics are retained to improve routing and service quality. If you wish to delete your account and associated data, contact us at the email below.
          </p>

          <h2>5. DATA SHARING</h2>
          <p>
            We share information with third parties only in the following circumstances:
          </p>
          <ul>
            <li><strong>AI Model Providers</strong> — Your request content is forwarded to third-party AI model providers (via OpenRouter) to process and generate responses. These providers have their own privacy policies governing data handling.</li>
            <li><strong>Infrastructure Providers</strong> — We use cloud infrastructure providers to host and operate the Service.</li>
            <li><strong>Payment Processors</strong> — Stripe processes payments on our behalf, subject to <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Stripe's Privacy Policy</a>.</li>
            <li><strong>Analytics</strong> — We use analytics services to understand website usage patterns.</li>
            <li><strong>Legal Requirements</strong> — We may disclose information if required by law, legal process, or government request, or to protect the rights, safety, or property of Herma, our users, or the public.</li>
          </ul>
          <p>
            We do not sell your personal information to third parties.
          </p>

          <h2>6. SECURITY</h2>
          <p>
            We implement commercially reasonable security measures to protect your information, including:
          </p>
          <ul>
            <li>Encryption at rest and in transit (TLS)</li>
            <li>Application-level encryption for sensitive stored data</li>
            <li>One-way hashed passwords and API keys</li>
            <li>Role-based access controls</li>
            <li>Comprehensive audit logging</li>
            <li>Regular security monitoring</li>
          </ul>
          <p>
            However, no method of transmission over the Internet or electronic storage is completely secure. We cannot guarantee absolute security.
          </p>

          <h2>7. YOUR RIGHTS</h2>
          <p>
            Depending on your location, you may have certain rights regarding your personal information, including the right to:
          </p>
          <ul>
            <li>Access the personal information we hold about you</li>
            <li>Request correction of inaccurate information</li>
            <li>Request deletion of your personal information</li>
            <li>Request portability of your data</li>
            <li>Object to or restrict certain processing activities</li>
            <li>Withdraw consent where processing is based on consent</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at the email below. We will respond to your request in accordance with applicable law.
          </p>

          <h2>8. CHILDREN'S PRIVACY</h2>
          <p>
            The Service is not directed to children under 13 (or the applicable age of digital consent in your jurisdiction). We do not knowingly collect personal information from children. If we learn that we have collected information from a child, we will take steps to delete it.
          </p>

          <h2>9. INTERNATIONAL DATA TRANSFERS</h2>
          <p>
            Your information may be transferred to and processed in countries other than your country of residence. We take steps to ensure that your information receives an adequate level of protection in the jurisdictions in which we process it.
          </p>

          <h2>10. CHANGES TO THIS POLICY</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on this page with a revised date. Your continued use of the Service after any changes constitutes your acceptance of the updated policy.
          </p>

          <div className="policy-contact">
            <p>
              For questions about this Privacy Policy or to exercise your privacy rights, contact us at:
            </p>
            <p>
              <a href="mailto:hermalocal@gmail.com">hermalocal@gmail.com</a>
            </p>
          </div>

          <p className="policy-updated">
            Last updated: February 24, 2026
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
